- name: Install Docker & JDK 11
  hosts: all
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - docker
    - openjdk11
