- name: Install Docker
  hosts: all
  become: yes
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - openjdk11
