---
    - name: Pull Wazuh Manager Docker image
      docker_image:
        name: wazuh/wazuh-manager
        tag: "4.7.4"
        source: pull

    - name: Run Wazuh Manager container
      docker_container:
        name: wazuh-manager
        image: wazuh/wazuh-manager:4.7.4
        state: started
        restart_policy: always
        ports:
          - "55000:55000"
          - "1514:1514/udp"
        volumes:
          - /var/ossec/data:/var/ossec/data

    - name: Pull Wazuh Indexer Docker image
      docker_image:
        name: wazuh/wazuh-indexer
        tag: "4.7.4"
        source: pull

    - name: Run Wazuh Indexer container
      docker_container:
        name: wazuh-indexer
        image: wazuh/wazuh-indexer:4.7.4
        state: started
        restart_policy: always

    - name: Pull Wazuh Dashboard Docker image
      docker_image:
        name: wazuh/wazuh-dashboard
        tag: "4.7.4"
        source: pull

    - name: Run Wazuh Dashboard container
      docker_container:
        name: wazuh-dashboard
        image: wazuh/wazuh-dashboard:4.7.4
        state: started
        restart_policy: always
        ports:
          - "8000:80"
