---
- name: Pull Wazuh Docker image
  docker_image:
    name: wazuh/wazuh
    tag: "v4.7.4"
    source: pull

- name: Create and start Wazuh Manager container
  docker_container:
    name: wazuh-manager
    image: wazuh/wazuh:v4.7.4
    state: started
    restart_policy: always
    ports:
      - "55000:55000"
      - "1514:1514/udp"
    volumes:
      - /var/ossec/data:/var/ossec/data
