[master]
master ansible_host=10.2.1.2 ansible_connection=ssh ansible_user=devops ansible_become_method=sudo ansible_become_password=devopsdevopsdevops ansible_python_interpreter=/usr/bin/python3

[workers]
worker1 ansible_host=10.2.1.1 ansible_connection=ssh ansible_user=ghada ansible_become_method=sudo ansible_become_password=ghada ansible_ssh_user=ghada ansible_ssh_pass=ghada
worker2 ansible_host=10.2.1.3 ansible_connection=ssh ansible_user=ghada ansible_become_method=sudo ansible_become_password=ghada ansible_ssh_user=ghada ansible_ssh_pass=ghada





